# Generated by Django 6.0.6 on 2026-06-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('pdf_name', models.CharField(blank=True, default='', max_length=200)),
                ('pdf_data_url', models.CharField(blank=True, default='', max_length=500)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_members', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('fin', models.CharField(db_index=True, max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('password_hash', models.CharField(blank=True, default='', max_length=256)),
                ('password_salt', models.CharField(blank=True, default='', max_length=64)),
                ('registered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField()),
                ('fin', models.CharField(db_index=True, max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(db_column='mentor_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.mentor')),
            ],
            options={
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('school', models.CharField(help_text='Country or organization name', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category_name', models.CharField(blank=True, default='', max_length=120)),
                ('mentor_name', models.CharField(blank=True, default='', max_length=240)),
                ('member_count', models.PositiveSmallIntegerField(default=0)),
                ('payment_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid')], default='', max_length=20)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Card'), ('bank_transfer', 'Bank transfer')], default='', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.category')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='teams.member')),
                ('mentor', models.ForeignKey(blank=True, db_column='mentor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.mentor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('mentor', 'email'), name='unique_member_email_per_mentor'),
        ),
    ]
